azure:
  key: azureKey
aws:
  key: awsKey
google:
  key: googleKey
on_premises:
  ip: ip-address
provider: AZURE
infrastructure: TRADITIONAL
authentication: none
functions:
  function_1:
      provider: AWS
      authentication: none
  function_2:
    provider: AZURE
    authentication: none