name: Build and Create Artifact
on:
  push:
    branches:
      - master

jobs:
  create-zip-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Zip Archive
        run: |
          zip library.zip config.sh config.yaml generate-docker-compose.sh get_all_java_files.py python-config.sh read_files.py read_yaml.py requirements.txt

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: library
          path: library.zip


  create-release:
    needs: create-zip-artifact # Der Job 'create-release' hängt von 'create-zip-artifact' ab.
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Stellen Sie sicher, dass 'GITHUB_TOKEN' verfügbar ist.
        with:
          tag_name: v1.0.0 # Ändern Sie dies entsprechend Ihrer Versionsnummer
          release_name: Release v1.0.0 # Ändern Sie dies entsprechend dem Namen Ihres Releases
          draft: false
          prerelease: false

      - name: Upload Artifact
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Stellen Sie sicher, dass 'GITHUB_TOKEN' verfügbar ist.
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: library.zip
          asset_name: library.zip
          asset_content_type: application/zip
