name: Build and Create Artifact
on:
  push:
    branches:
      - master

jobs:
  create-zip-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Zip Archive
        run: |
          zip library.zip config.sh config.yaml generate-docker-compose.sh get_all_java_files.py python-config.sh read_files.py read_yaml.py requirements.txt

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: library
          path: library.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}